name: Release

on:
  push:
    tags: ["v[1-9]+.[0-9]+.[0-9]+"]
    branches: [main]

jobs:
  auto-release:
    name: Bundle release
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          zip unzip wget jq cmake musl-dev musl musl-tools build-essential
          
      - name: Minisign
        run: |
          MINISIGN_TMP=`mktemp -d`
          cd $MINISIGN_TMP
          wget https://github.com/aead/minisign/releases/download/v0.2.0/minisign-linux-amd64.tar.gz
          tar xvf minisign-linux-amd64.tar.gz
          mv ./minisign ~/minisign
    
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build
          tar -czvf libreflect.tar.gz ${{github.workspace}}/build/libreflect.x86_64.a

      - name: Sign Package
        run: |
          touch ~/minisign.key && chmod 600 ~/minisign.key
          echo -e "${{ secrets.MINISIGN_PRIVATE_KEY }}" > ~/minisign.key
          COMMENT=$(sha256sum libreflect.tar.gz)
          bash -c "echo \"\" | ~/minisign -s ~/minisign.key -S -m ./libreflect.tar.gz -t \"$COMMENT\" -x libreflect.minisig"
          
      - name: "Publish Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./libreflect.tar.gz
            ./libreflect.minisig
